### PR TITLE
Chef-vault support + simple data bag layout

### PR DESCRIPTION
**Pull request by bitphage**

### CODE REVIEW

**Comment by aspyatkin** [comment]
@bitfag Thank you for your contribution. I've never used Chef Vault before, so I will need some time to get some information about it and figure out whether it's worth adding this method of obtaining SSH keys to this cookbook. Strictly speaking, I'd prefer to keep it as simple as possible.

**Comment by bitphage** [comment]
22.02.2017, 08:51, "Alexander Pyatkin" <notifications@github.com>:
> @bitfag Thank you for your contribution. I've never used Chef Vault before, so I will need some time to get some information about it and figure out whether it's worth adding this method of obtaining SSH keys to this cookbook. Strictly speaking, I'd prefer to keep it as simple as possible.

OK. Btw, I'll update the PR some later, there are few things need to be corrected. Chef-vault is widely used. Also, environments are in deprecation way in favor to Policyfiles.

**Comment by aspyatkin** [comment]
I would consider adding `Gemfile` with the following content:
```ruby
source 'https://rubygems.org'

gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'berkshelf'
gem 'kitchen-chefzero-nodes'
gem 'kitchen-inspec'
```

I do not have Chef-DK installed on my system, so for me it's the only way I could run tests with `bundle exec kitchen test`.

Also, to avoid confusion with the repository folder name, I would suggest replacing this line in the `Policyfile.rb`:
```
cookbook "ssh-private-keys", path: "../ssh-private-keys"
```
with the following one:
```
cookbook "ssh-private-keys", path: '.'
```

Besides, as far as I can see from the source code, attribute `data_bag_layout ` is now actually of String type, and in description there is some misleading information about it.

Finally, would you please add extra two tests so as to cover `advanced` layout case?

**Comment by bitphage** [comment]
> Finally, would you please add extra two tests so as to cover `advanced` layout case?

Actually I tried this but unfortunately environments are not supported with `policyfile_zero` provisioner.

**Pull request merged**
